/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserMyCollectionRouteImport } from './routes/user/my-collection'
import { Route as UserLedgerRouteImport } from './routes/user/ledger'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthHomeRouteImport } from './routes/auth/home'
import { Route as UserMyCollectionIndexRouteImport } from './routes/user/my-collection/index'
import { Route as UserMyCollectionCollection_item_idRouteImport } from './routes/user/my-collection/$collection_item_id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMyCollectionRoute = UserMyCollectionRouteImport.update({
  id: '/my-collection',
  path: '/my-collection',
  getParentRoute: () => UserRoute,
} as any)
const UserLedgerRoute = UserLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const UserMyCollectionIndexRoute = UserMyCollectionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserMyCollectionRoute,
} as any)
const UserMyCollectionCollection_item_idRoute =
  UserMyCollectionCollection_item_idRouteImport.update({
    id: '/$collection_item_id',
    path: '/$collection_item_id',
    getParentRoute: () => UserMyCollectionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/auth/home': typeof AuthHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/ledger': typeof UserLedgerRoute
  '/user/my-collection': typeof UserMyCollectionRouteWithChildren
  '/user/my-collection/$collection_item_id': typeof UserMyCollectionCollection_item_idRoute
  '/user/my-collection/': typeof UserMyCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/auth/home': typeof AuthHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/ledger': typeof UserLedgerRoute
  '/user/my-collection/$collection_item_id': typeof UserMyCollectionCollection_item_idRoute
  '/user/my-collection': typeof UserMyCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/auth/home': typeof AuthHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/signup': typeof AuthSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/ledger': typeof UserLedgerRoute
  '/user/my-collection': typeof UserMyCollectionRouteWithChildren
  '/user/my-collection/$collection_item_id': typeof UserMyCollectionCollection_item_idRoute
  '/user/my-collection/': typeof UserMyCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/user'
    | '/auth/home'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/user/dashboard'
    | '/user/ledger'
    | '/user/my-collection'
    | '/user/my-collection/$collection_item_id'
    | '/user/my-collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/user'
    | '/auth/home'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/user/dashboard'
    | '/user/ledger'
    | '/user/my-collection/$collection_item_id'
    | '/user/my-collection'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/user'
    | '/auth/home'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/signup'
    | '/user/dashboard'
    | '/user/ledger'
    | '/user/my-collection'
    | '/user/my-collection/$collection_item_id'
    | '/user/my-collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/my-collection': {
      id: '/user/my-collection'
      path: '/my-collection'
      fullPath: '/user/my-collection'
      preLoaderRoute: typeof UserMyCollectionRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/ledger': {
      id: '/user/ledger'
      path: '/ledger'
      fullPath: '/user/ledger'
      preLoaderRoute: typeof UserLedgerRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/home': {
      id: '/auth/home'
      path: '/home'
      fullPath: '/auth/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/user/my-collection/': {
      id: '/user/my-collection/'
      path: '/'
      fullPath: '/user/my-collection/'
      preLoaderRoute: typeof UserMyCollectionIndexRouteImport
      parentRoute: typeof UserMyCollectionRoute
    }
    '/user/my-collection/$collection_item_id': {
      id: '/user/my-collection/$collection_item_id'
      path: '/$collection_item_id'
      fullPath: '/user/my-collection/$collection_item_id'
      preLoaderRoute: typeof UserMyCollectionCollection_item_idRouteImport
      parentRoute: typeof UserMyCollectionRoute
    }
  }
}

interface AuthRouteChildren {
  AuthHomeRoute: typeof AuthHomeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHomeRoute: AuthHomeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserMyCollectionRouteChildren {
  UserMyCollectionCollection_item_idRoute: typeof UserMyCollectionCollection_item_idRoute
  UserMyCollectionIndexRoute: typeof UserMyCollectionIndexRoute
}

const UserMyCollectionRouteChildren: UserMyCollectionRouteChildren = {
  UserMyCollectionCollection_item_idRoute:
    UserMyCollectionCollection_item_idRoute,
  UserMyCollectionIndexRoute: UserMyCollectionIndexRoute,
}

const UserMyCollectionRouteWithChildren =
  UserMyCollectionRoute._addFileChildren(UserMyCollectionRouteChildren)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserLedgerRoute: typeof UserLedgerRoute
  UserMyCollectionRoute: typeof UserMyCollectionRouteWithChildren
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserLedgerRoute: UserLedgerRoute,
  UserMyCollectionRoute: UserMyCollectionRouteWithChildren,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
