/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as HomeSignupRouteImport } from './routes/home/signup'
import { Route as HomeOtpRouteImport } from './routes/home/otp'
import { Route as HomeLoginRouteImport } from './routes/home/login'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const HomeSignupRoute = HomeSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => HomeRoute,
} as any)
const HomeOtpRoute = HomeOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLoginRoute = HomeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/home/login': typeof HomeLoginRoute
  '/home/otp': typeof HomeOtpRoute
  '/home/signup': typeof HomeSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/user': typeof UserRouteWithChildren
  '/home/login': typeof HomeLoginRoute
  '/home/otp': typeof HomeOtpRoute
  '/home/signup': typeof HomeSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/home': typeof HomeRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/home/login': typeof HomeLoginRoute
  '/home/otp': typeof HomeOtpRoute
  '/home/signup': typeof HomeSignupRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/user'
    | '/home/login'
    | '/home/otp'
    | '/home/signup'
    | '/user/dashboard'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user'
    | '/home/login'
    | '/home/otp'
    | '/home/signup'
    | '/user/dashboard'
    | '/home'
  id:
    | '__root__'
    | '/home'
    | '/user'
    | '/home/login'
    | '/home/otp'
    | '/home/signup'
    | '/user/dashboard'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRoute: typeof HomeRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/home/signup': {
      id: '/home/signup'
      path: '/signup'
      fullPath: '/home/signup'
      preLoaderRoute: typeof HomeSignupRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/otp': {
      id: '/home/otp'
      path: '/otp'
      fullPath: '/home/otp'
      preLoaderRoute: typeof HomeOtpRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/login': {
      id: '/home/login'
      path: '/login'
      fullPath: '/home/login'
      preLoaderRoute: typeof HomeLoginRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeLoginRoute: typeof HomeLoginRoute
  HomeOtpRoute: typeof HomeOtpRoute
  HomeSignupRoute: typeof HomeSignupRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeLoginRoute: HomeLoginRoute,
  HomeOtpRoute: HomeOtpRoute,
  HomeSignupRoute: HomeSignupRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HomeRoute: HomeRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
